### PR TITLE
Migrate GitHub Action

### PR DESCRIPTION
**Pull request by odanado**
Close: #19

### CODE REVIEW

**Comment by mmktomato** [comment]
Looks good.

@vvatanabe What do you think? I'm not so familiar with GitHub Actions that I want your opinion :bow:

**Comment by vvatanabe** [comment]
LGTM;D

**Comment by vvatanabe** [comment]
If it works, let's remove the TravisCI setting.

**Comment by mmktomato** [comment]
Thanks.
I'll merge and let's see how it works.

**Comment by vvatanabe** [comment]
@mmktomato We can change the Readme badge to a GitHub action ;D

**Pull request merged**
